export const timelineTasks = [
    {
        id: 1,
        title: "DearPyGUI Platforms",
        cycle: "Cycle 1",
        status: "Done",
        deadline: "Oct 13, 2024",
    },
    {
        id: 2,
        title: "Data Designer Cycle 1",
        cycle: "Cycle 1",
        status: "Update",
        deadline: "Oct 31, 2024",
    },
    {
        id: 3,
        title: "Agent Manager Cycle 1",
        cycle: "Cycle 1",
        status: "Done",
        deadline: "Oct 25, 2024",
    },
    {
        id: 4,
        title: "Cluster Manager Cycle 1",
        cycle: "Cycle 1",
        status: "Update",
        deadline: "Oct 31, 2024",
    },
    {
        id: 5,
        title: "Documentation Cycle 1",
        cycle: "Cycle 1",
        status: "Done",
        deadline: "Oct 13, 2024",
    },
    {
        id: 6,
        title: "Model Designer Cycle 1",
        cycle: "Cycle 1",
        status: "Update",
        deadline: "Oct 28, 2024",
    },
    {
        id: 7,
        title: "Model Designer Cycle 2",
        cycle: "Cycle 2",
        status: "Done",
        deadline: "Nov 8, 2024",
    },
    {
        id: 8,
        title: "Cluster Manager Cycle 2",
        cycle: "Cycle 2",
        status: "Late In Progress",
        deadline: "Nov 8, 2024",
    },
    {
        id: 9,
        title: "Agent Manager Cycle 2",
        cycle: "Cycle 2",
        status: "Late In Progress",
        deadline: "Nov 8, 2024",
    },
    {
        id: 10,
        title: "Data Designer Cycle 2",
        cycle: "Cycle 2",
        status: "Done",
        deadline: "Nov 8, 2024",
    },
    {
        id: 11,
        title: "Agent Benchmark Cycle 2&3",
        cycle: "Cycle 2",
        status: "Done",
        deadline: "Nov 8, 2024",
    },
    {
        id: 12,
        title: "Model Designer Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 3",
        status: "Update",
        deadline: "Nov 18, 2024",
    },
    {
        id: 13,
        title: "Agents Manager Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Late In Progress",
        deadline: "Dec 3, 2024",
    },
    {
        id: 14,
        title: "Agents Benchmark Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Done",
        deadline: "Dec 1, 2024",
    },
    {
        id: 15,
        title: "Cluster Manager Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Late In Progress",
        deadline: "Dec 8, 2024",
    },
    {
        id: 16,
        title: "Cluster Benchmark Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Critical",
        deadline: "Dec 7, 2024",
    },
    {
        id: 17,
        title: "Data Designer Cycle 3&4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Done",
        deadline: "Dec 1, 2024",
    },
    {
        id: 18,
        title: "Markets Cycle 4 (Alpha Release)",
        cycle: "Cycle 4",
        status: "Update",
        deadline: "Dec 6, 2024",
    },
    {
        id: 19,
        title: "Units Tests & CI/CD Action & Code Coverage & Documentation",
        cycle: "Cycle 4",
        status: "In Progress",
        deadline: "Jan 31, 2025",
    },
    {
        id: 20,
        title: "Create a web site",
        cycle: "Cycle 4",
        status: "In Progress",
        deadline: "Jan 31, 2025",
    },
];